# Analyzing CIA Factbook

In this project, I am going to work data from CIA World Factbook which data about population, population growth, and area of land-water of countries all over the world. 
For more info please visit website:
https://www.cia.gov/the-world-factbook/

In [1]:
!conda install -yc conda-forge ipython-sql

/bin/sh: 1: conda: not found

In [2]:
%%capture
%load_ext sql
%sql sqlite:///factbook.db

'Connected: None@factbook.db'

In [11]:
%%sql
SELECT *
FROM facts
LIMIT 5;

Done.

[(1, 'af', 'Afghanistan', 652230, 652230, 0, 32564342, 2.32, 38.57, 13.89, 1.51),
 (2, 'al', 'Albania', 28748, 27398, 1350, 3029278, 0.3, 12.92, 6.58, 3.3),
 (3, 'ag', 'Algeria', 2381741, 2381741, 0, 39542166, 1.84, 23.67, 4.31, 0.92),
 (4, 'an', 'Andorra', 468, 468, 0, 85580, 0.12, 8.13, 6.96, 0.0),
 (5, 'ao', 'Angola', 1246700, 1246700, 0, 19625353, 2.78, 38.78, 11.49, 0.46)]

These are description of the data

name — the name of the country.
area— the country's total area (both land and water).
area_land — the country's land area in square kilometers.
area_water — the country's waterarea in square kilometers.
population — the country's population.
population_growth— the country's population growth as a percentage.
birth_rate — the country's birth rate, or the number of births per year per 1,000 people.
death_rate — the country's death rate, or the number of death per year per 1,000 people.

In [12]:
%%sql
SELECT MIN(population), MAX(population),
        MIN(population_growth), MAX(population_growth)
FROM facts

Done.

[(0, 7256490011, 0.0, 4.02)]

There is problem with our dataset which population is 0 and population growing is 0.

In [19]:
%%sql
SELECT name, population
FROM facts
ORDER BY population

Done.

[('Ashmore and Cartier Islands', None),
 ('Coral Sea Islands', None),
 ('Heard Island and McDonald Islands', None),
 ('Clipperton Island', None),
 ('French Southern and Antarctic Lands', None),
 ('Bouvet Island', None),
 ('Jan Mayen', None),
 ('British Indian Ocean Territory', None),
 ('South Georgia and South Sandwich Islands', None),
 ('Navassa Island', None),
 ('Wake Island', None),
 ('United States Pacific Island Wildlife Refuges', None),
 ('Paracel Islands', None),
 ('Spratly Islands', None),
 ('Arctic Ocean', None),
 ('Atlantic Ocean', None),
 ('Indian Ocean', None),
 ('Pacific Ocean', None),
 ('Southern Ocean', None),
 ('Antarctica', 0),
 ('Pitcairn Islands', 48),
 ('Cocos (Keeling) Islands', 596),
 ('Holy See (Vatican City)', 842),
 ('Niue', 1190),
 ('Tokelau', 1337),
 ('Christmas Island', 1530),
 ('Svalbard', 1872),
 ('Norfolk Island', 2210),
 ('Falkland Islands (Islas Malvinas)', 3361),
 ('Montserrat', 5241),
 ('Saint Pierre and Miquelon', 5657),
 ('Saint Barthelemy', 7237),
 ('Saint Helena, Ascension, and Tristan da Cunha', 7795),
 ('Nauru', 9540),
 ('Cook Islands', 9838),
 ('Tuvalu', 10869),
 ('Wallis and Futuna', 15613),
 ('Akrotiri', 15700),
 ('Dhekelia', 15700),
 ('Anguilla', 16418),
 ('Palau', 21265),
 ('Gibraltar', 29258),
 ('Monaco', 30535),
 ('Saint Martin', 31754),
 ('San Marino', 33020),
 ('British Virgin Islands', 33454),
 ('Liechtenstein', 37624),
 ('Sint Maarten', 39689),
 ('Faroe Islands', 50196),
 ('Turks and Caicos Islands', 50280),
 ('Saint Kitts and Nevis', 51936),
 ('Northern Mariana Islands', 52344),
 ('American Samoa', 54343),
 ('Cayman Islands', 56092),
 ('Greenland', 57733),
 ('Guernsey', 66080),
 ('Bermuda', 70196),
 ('Marshall Islands', 72191),
 ('Dominica', 73607),
 ('Andorra', 85580),
 ('Isle of Man', 87545),
 ('Seychelles', 92430),
 ('Antigua and Barbuda', 92436),
 ('Jersey', 97294),
 ('Saint Vincent and the Grenadines', 102627),
 ('Virgin Islands', 103574),
 ('Micronesia, Federated States of', 105216),
 ('Kiribati', 105711),
 ('Tonga', 106501),
 ('Grenada', 110694),
 ('Aruba', 112162),
 ('Curacao', 148406),
 ('Guam', 161785),
 ('Saint Lucia', 163922),
 ('Sao Tome and Principe', 194006),
 ('Samoa', 197773),
 ('New Caledonia', 271615),
 ('Vanuatu', 272264),
 ('French Polynesia', 282703),
 ('Barbados', 290604),
 ('Bahamas, The', 324597),
 ('Iceland', 331918),
 ('Belize', 347369),
 ('Maldives', 393253),
 ('Malta', 413965),
 ('Brunei', 429646),
 ('Cabo Verde', 545993),
 ('Luxembourg', 570252),
 ('Western Sahara', 570866),
 ('Suriname', 579633),
 ('Macau', 592731),
 ('Solomon Islands', 622469),
 ('Montenegro', 647073),
 ('Guyana', 735222),
 ('Equatorial Guinea', 740743),
 ('Bhutan', 741919),
 ('Comoros', 780971),
 ('Djibouti', 828324),
 ('Fiji', 909389),
 ('Cyprus', 1189197),
 ('Trinidad and Tobago', 1222363),
 ('Timor-Leste', 1231116),
 ('Estonia', 1265420),
 ('Mauritius', 1339827),
 ('Bahrain', 1346613),
 ('Swaziland', 1435613),
 ('Gabon', 1705336),
 ('Guinea-Bissau', 1726170),
 ('Gaza Strip', 1869055),
 ('Kosovo', 1870981),
 ('Lesotho', 1947701),
 ('Gambia, The', 1967709),
 ('Slovenia', 1983412),
 ('Latvia', 1986705),
 ('Macedonia', 2096015),
 ('Botswana', 2182719),
 ('Qatar', 2194817),
 ('Namibia', 2212307),
 ('West Bank', 2785366),
 ('Kuwait', 2788534),
 ('Lithuania', 2884433),
 ('Jamaica', 2950210),
 ('Mongolia', 2992908),
 ('Albania', 3029278),
 ('Armenia', 3056382),
 ('Oman', 3286936),
 ('Uruguay', 3341893),
 ('Moldova', 3546847),
 ('Mauritania', 3596702),
 ('Puerto Rico', 3598357),
 ('Panama', 3657024),
 ('Bosnia and Herzegovina', 3867055),
 ('Liberia', 4195666),
 ('New Zealand', 4438393),
 ('Croatia', 4464844),
 ('Congo, Republic of the', 4755097),
 ('Costa Rica', 4814144),
 ('Ireland', 4892305),
 ('Georgia', 4931226),
 ('Norway', 5207689),
 ('Turkmenistan', 5231422),
 ('Central African Republic', 5391539),
 ('Slovakia', 5445027),
 ('Finland', 5476922),
 ('Denmark', 5581503),
 ('Kyrgyzstan', 5664939),
 ('Singapore', 5674472),
 ('United Arab Emirates', 5779760),
 ('Sierra Leone', 5879098),
 ('Nicaragua', 5907881),
 ('El Salvador', 6141350),
 ('Lebanon', 6184701),
 ('Libya', 6411776),
 ('Eritrea', 6527689),
 ('Papua New Guinea', 6672429),
 ('Paraguay', 6783272),
 ('Laos', 6911544),
 ('Hong Kong', 7141106),
 ('Serbia', 7176794),
 ('Bulgaria', 7186893),
 ('Togo', 7552318),
 ('Israel', 8049314),
 ('Jordan', 8117564),
 ('Switzerland', 8121830),
 ('Tajikistan', 8191958),
 ('Austria', 8665550),
 ('Honduras', 8746673),
 ('Belarus', 9589689),
 ('Azerbaijan', 9780780),
 ('Sweden', 9801616),
 ('Hungary', 9897541),
 ('Haiti', 10110019),
 ('Benin', 10448647),
 ('Dominican Republic', 10478756),
 ('Somalia', 10616380),
 ('Czech Republic', 10644842),
 ('Burundi', 10742276),
 ('Greece', 10775643),
 ('Bolivia', 10800882),
 ('Portugal', 10825309),
 ('Cuba', 11031433),
 ('Tunisia', 11037225),
 ('Belgium', 11323973),
 ('Chad', 11631456),
 ('Guinea', 11780162),
 ('South Sudan', 12042910),
 ('Rwanda', 12661733),
 ('Senegal', 13975834),
 ('Zimbabwe', 14229541),
 ('Guatemala', 14918999),
 ('Zambia', 15066266),
 ('Cambodia', 15708756),
 ('Ecuador', 15868396),
 ('Netherlands', 16947904),
 ('Mali', 16955536),
 ('Syria', 17064854),
 ('Chile', 17508260),
 ('Malawi', 17964697),
 ('Niger', 18045729),
 ('Kazakhstan', 18157122),
 ('Burkina Faso', 18931686),
 ('Angola', 19625353),
 ('Romania', 21666350),
 ('Sri Lanka', 22053488),
 ('Australia', 22751014),
 ("Cote d'Ivoire", 23295302),
 ('Taiwan', 23415126),
 ('Cameroon', 23739218),
 ('Madagascar', 23812681),
 ('Korea, North', 24983205),
 ('Mozambique', 25303113),
 ('Ghana', 26327649),
 ('Yemen', 26737317),
 ('Saudi Arabia', 27752316),
 ('Uzbekistan', 29199942),
 ('Venezuela', 29275460),
 ('Peru', 30444999),
 ('Malaysia', 30513848),
 ('Nepal', 31551305),
 ('Afghanistan', 32564342),
 ('Morocco', 33322699),
 ('Canada', 35099836),
 ('Sudan', 36108853),
 ('Iraq', 37056169),
 ('Uganda', 37101745),
 ('Poland', 38562189),
 ('Algeria', 39542166),
 ('Argentina', 43431886),
 ('Ukraine', 44429471),
 ('Kenya', 45925301),
 ('Colombia', 46736728),
 ('Spain', 48146134),
 ('Korea, South', 49115196),
 ('Tanzania', 51045882),
 ('South Africa', 53675563),
 ('Burma', 56320206),
 ('Italy', 61855120),
 ('United Kingdom', 64088222),
 ('France', 66553766),
 ('Thailand', 67976405),
 ('Congo, Democratic Republic of the', 79375136),
 ('Turkey', 79414269),
 ('Germany', 80854408),
 ('Iran', 81824270),
 ('Egypt', 88487396),
 ('Vietnam', 94348835),
 ('Ethiopia', 99465819),
 ('Philippines', 100998376),
 ('Mexico', 121736809),
 ('Japan', 126919659),
 ('Russia', 142423773),
 ('Bangladesh', 168957745),
 ('Nigeria', 181562056),
 ('Pakistan', 199085847),
 ('Brazil', 204259812),
 ('Indonesia', 255993674),
 ('United States', 321368864),
 ('European Union', 513949445),
 ('India', 1251695584),
 ('China', 1367485388),
 ('World', 7256490011)]

In [20]:
%%sql
SELECT name, population
FROM facts
ORDER BY population DESC;

Done.

[('World', 7256490011),
 ('China', 1367485388),
 ('India', 1251695584),
 ('European Union', 513949445),
 ('United States', 321368864),
 ('Indonesia', 255993674),
 ('Brazil', 204259812),
 ('Pakistan', 199085847),
 ('Nigeria', 181562056),
 ('Bangladesh', 168957745),
 ('Russia', 142423773),
 ('Japan', 126919659),
 ('Mexico', 121736809),
 ('Philippines', 100998376),
 ('Ethiopia', 99465819),
 ('Vietnam', 94348835),
 ('Egypt', 88487396),
 ('Iran', 81824270),
 ('Germany', 80854408),
 ('Turkey', 79414269),
 ('Congo, Democratic Republic of the', 79375136),
 ('Thailand', 67976405),
 ('France', 66553766),
 ('United Kingdom', 64088222),
 ('Italy', 61855120),
 ('Burma', 56320206),
 ('South Africa', 53675563),
 ('Tanzania', 51045882),
 ('Korea, South', 49115196),
 ('Spain', 48146134),
 ('Colombia', 46736728),
 ('Kenya', 45925301),
 ('Ukraine', 44429471),
 ('Argentina', 43431886),
 ('Algeria', 39542166),
 ('Poland', 38562189),
 ('Uganda', 37101745),
 ('Iraq', 37056169),
 ('Sudan', 36108853),
 ('Canada', 35099836),
 ('Morocco', 33322699),
 ('Afghanistan', 32564342),
 ('Nepal', 31551305),
 ('Malaysia', 30513848),
 ('Peru', 30444999),
 ('Venezuela', 29275460),
 ('Uzbekistan', 29199942),
 ('Saudi Arabia', 27752316),
 ('Yemen', 26737317),
 ('Ghana', 26327649),
 ('Mozambique', 25303113),
 ('Korea, North', 24983205),
 ('Madagascar', 23812681),
 ('Cameroon', 23739218),
 ('Taiwan', 23415126),
 ("Cote d'Ivoire", 23295302),
 ('Australia', 22751014),
 ('Sri Lanka', 22053488),
 ('Romania', 21666350),
 ('Angola', 19625353),
 ('Burkina Faso', 18931686),
 ('Kazakhstan', 18157122),
 ('Niger', 18045729),
 ('Malawi', 17964697),
 ('Chile', 17508260),
 ('Syria', 17064854),
 ('Mali', 16955536),
 ('Netherlands', 16947904),
 ('Ecuador', 15868396),
 ('Cambodia', 15708756),
 ('Zambia', 15066266),
 ('Guatemala', 14918999),
 ('Zimbabwe', 14229541),
 ('Senegal', 13975834),
 ('Rwanda', 12661733),
 ('South Sudan', 12042910),
 ('Guinea', 11780162),
 ('Chad', 11631456),
 ('Belgium', 11323973),
 ('Tunisia', 11037225),
 ('Cuba', 11031433),
 ('Portugal', 10825309),
 ('Bolivia', 10800882),
 ('Greece', 10775643),
 ('Burundi', 10742276),
 ('Czech Republic', 10644842),
 ('Somalia', 10616380),
 ('Dominican Republic', 10478756),
 ('Benin', 10448647),
 ('Haiti', 10110019),
 ('Hungary', 9897541),
 ('Sweden', 9801616),
 ('Azerbaijan', 9780780),
 ('Belarus', 9589689),
 ('Honduras', 8746673),
 ('Austria', 8665550),
 ('Tajikistan', 8191958),
 ('Switzerland', 8121830),
 ('Jordan', 8117564),
 ('Israel', 8049314),
 ('Togo', 7552318),
 ('Bulgaria', 7186893),
 ('Serbia', 7176794),
 ('Hong Kong', 7141106),
 ('Laos', 6911544),
 ('Paraguay', 6783272),
 ('Papua New Guinea', 6672429),
 ('Eritrea', 6527689),
 ('Libya', 6411776),
 ('Lebanon', 6184701),
 ('El Salvador', 6141350),
 ('Nicaragua', 5907881),
 ('Sierra Leone', 5879098),
 ('United Arab Emirates', 5779760),
 ('Singapore', 5674472),
 ('Kyrgyzstan', 5664939),
 ('Denmark', 5581503),
 ('Finland', 5476922),
 ('Slovakia', 5445027),
 ('Central African Republic', 5391539),
 ('Turkmenistan', 5231422),
 ('Norway', 5207689),
 ('Georgia', 4931226),
 ('Ireland', 4892305),
 ('Costa Rica', 4814144),
 ('Congo, Republic of the', 4755097),
 ('Croatia', 4464844),
 ('New Zealand', 4438393),
 ('Liberia', 4195666),
 ('Bosnia and Herzegovina', 3867055),
 ('Panama', 3657024),
 ('Puerto Rico', 3598357),
 ('Mauritania', 3596702),
 ('Moldova', 3546847),
 ('Uruguay', 3341893),
 ('Oman', 3286936),
 ('Armenia', 3056382),
 ('Albania', 3029278),
 ('Mongolia', 2992908),
 ('Jamaica', 2950210),
 ('Lithuania', 2884433),
 ('Kuwait', 2788534),
 ('West Bank', 2785366),
 ('Namibia', 2212307),
 ('Qatar', 2194817),
 ('Botswana', 2182719),
 ('Macedonia', 2096015),
 ('Latvia', 1986705),
 ('Slovenia', 1983412),
 ('Gambia, The', 1967709),
 ('Lesotho', 1947701),
 ('Kosovo', 1870981),
 ('Gaza Strip', 1869055),
 ('Guinea-Bissau', 1726170),
 ('Gabon', 1705336),
 ('Swaziland', 1435613),
 ('Bahrain', 1346613),
 ('Mauritius', 1339827),
 ('Estonia', 1265420),
 ('Timor-Leste', 1231116),
 ('Trinidad and Tobago', 1222363),
 ('Cyprus', 1189197),
 ('Fiji', 909389),
 ('Djibouti', 828324),
 ('Comoros', 780971),
 ('Bhutan', 741919),
 ('Equatorial Guinea', 740743),
 ('Guyana', 735222),
 ('Montenegro', 647073),
 ('Solomon Islands', 622469),
 ('Macau', 592731),
 ('Suriname', 579633),
 ('Western Sahara', 570866),
 ('Luxembourg', 570252),
 ('Cabo Verde', 545993),
 ('Brunei', 429646),
 ('Malta', 413965),
 ('Maldives', 393253),
 ('Belize', 347369),
 ('Iceland', 331918),
 ('Bahamas, The', 324597),
 ('Barbados', 290604),
 ('French Polynesia', 282703),
 ('Vanuatu', 272264),
 ('New Caledonia', 271615),
 ('Samoa', 197773),
 ('Sao Tome and Principe', 194006),
 ('Saint Lucia', 163922),
 ('Guam', 161785),
 ('Curacao', 148406),
 ('Aruba', 112162),
 ('Grenada', 110694),
 ('Tonga', 106501),
 ('Kiribati', 105711),
 ('Micronesia, Federated States of', 105216),
 ('Virgin Islands', 103574),
 ('Saint Vincent and the Grenadines', 102627),
 ('Jersey', 97294),
 ('Antigua and Barbuda', 92436),
 ('Seychelles', 92430),
 ('Isle of Man', 87545),
 ('Andorra', 85580),
 ('Dominica', 73607),
 ('Marshall Islands', 72191),
 ('Bermuda', 70196),
 ('Guernsey', 66080),
 ('Greenland', 57733),
 ('Cayman Islands', 56092),
 ('American Samoa', 54343),
 ('Northern Mariana Islands', 52344),
 ('Saint Kitts and Nevis', 51936),
 ('Turks and Caicos Islands', 50280),
 ('Faroe Islands', 50196),
 ('Sint Maarten', 39689),
 ('Liechtenstein', 37624),
 ('British Virgin Islands', 33454),
 ('San Marino', 33020),
 ('Saint Martin', 31754),
 ('Monaco', 30535),
 ('Gibraltar', 29258),
 ('Palau', 21265),
 ('Anguilla', 16418),
 ('Akrotiri', 15700),
 ('Dhekelia', 15700),
 ('Wallis and Futuna', 15613),
 ('Tuvalu', 10869),
 ('Cook Islands', 9838),
 ('Nauru', 9540),
 ('Saint Helena, Ascension, and Tristan da Cunha', 7795),
 ('Saint Barthelemy', 7237),
 ('Saint Pierre and Miquelon', 5657),
 ('Montserrat', 5241),
 ('Falkland Islands (Islas Malvinas)', 3361),
 ('Norfolk Island', 2210),
 ('Svalbard', 1872),
 ('Christmas Island', 1530),
 ('Tokelau', 1337),
 ('Niue', 1190),
 ('Holy See (Vatican City)', 842),
 ('Cocos (Keeling) Islands', 596),
 ('Pitcairn Islands', 48),
 ('Antarctica', 0),
 ('Ashmore and Cartier Islands', None),
 ('Coral Sea Islands', None),
 ('Heard Island and McDonald Islands', None),
 ('Clipperton Island', None),
 ('French Southern and Antarctic Lands', None),
 ('Bouvet Island', None),
 ('Jan Mayen', None),
 ('British Indian Ocean Territory', None),
 ('South Georgia and South Sandwich Islands', None),
 ('Navassa Island', None),
 ('Wake Island', None),
 ('United States Pacific Island Wildlife Refuges', None),
 ('Paracel Islands', None),
 ('Spratly Islands', None),
 ('Arctic Ocean', None),
 ('Atlantic Ocean', None),
 ('Indian Ocean', None),
 ('Pacific Ocean', None),
 ('Southern Ocean', None)]

In [23]:
%%sql
SELECT *
FROM facts
WHERE population IN (SELECT MIN(population)
         FROM facts)

Done.

[(250, 'ay', 'Antarctica', None, 280000, None, 0, None, None, None, None)]

In [24]:
%%sql
SELECT *
FROM facts
WHERE population IN (SELECT MAX(population)
         FROM facts)

Done.

[(261, 'xx', 'World', None, None, None, 7256490011, 1.08, 18.6, 7.8, None)]

# As we look into deeply we see there is a world population and antarctica population which create outliers

In [26]:
%%sql
SELECT MIN(population), MAX(population),
        MIN(population_growth), MAX(population_growth)
FROM facts
WHERE name <> 'World';

Done.

[(0, 1367485388, 0.0, 4.02)]

In [35]:
%%sql
SELECT AVG(population), AVG(area)
    FROM facts
  WHERE name <> "World";

Done.

[(32242666.56846473, 555093.546184739)]

to find countries that are densely populated
-Above-average values for population.
-Below-average values for area.

In [47]:
%%sql
SELECT name, population, area
    FROM facts
WHERE population > (SELECT AVG(population)
                   FROM facts
                   WHERE name <> 'World')
    AND area < (SELECT AVG(area)
               FROM facts
               WHERE name <> 'World');

Done.

[('Bangladesh', 168957745, 148460),
 ('Germany', 80854408, 357022),
 ('Iraq', 37056169, 438317),
 ('Italy', 61855120, 301340),
 ('Japan', 126919659, 377915),
 ('Korea, South', 49115196, 99720),
 ('Morocco', 33322699, 446550),
 ('Philippines', 100998376, 300000),
 ('Poland', 38562189, 312685),
 ('Spain', 48146134, 505370),
 ('Thailand', 67976405, 513120),
 ('Uganda', 37101745, 241038),
 ('United Kingdom', 64088222, 243610),
 ('Vietnam', 94348835, 331210)]

There are some questions from the projects
Which country has the most people? Which country has the highest growth rate?

In [57]:
%%sql 
SELECT name, MAX(population)
FROM facts
WHERE name <> "World"

Done.

[('China', 1367485388)]

In [56]:
%%sql 
SELECT name, MAX(population_growth)
FROM facts
WHERE name <> "World"

Done.

[('South Sudan', 4.02)]